// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_lee_defeated = "CgkI5NK_j-IfEAIQCQ"; // <GPGSID>
        public const string leaderboard_master_of_masters = "CgkI5NK_j-IfEAIQBw"; // <GPGSID>
        public const string achievement_flying_solo = "CgkI5NK_j-IfEAIQBg"; // <GPGSID>
        public const string event_2p_match_ended = "CgkI5NK_j-IfEAIQEA"; // <GPGSID>
        public const string achievement_seasonal_collector = "CgkI5NK_j-IfEAIQAQ"; // <GPGSID>
        public const string achievement_the_journey_ends = "CgkI5NK_j-IfEAIQBA"; // <GPGSID>
        public const string event_murugam_defeated = "CgkI5NK_j-IfEAIQCg"; // <GPGSID>
        public const string event_kamal_defeated = "CgkI5NK_j-IfEAIQCw"; // <GPGSID>
        public const string achievement_congkak_student = "CgkI5NK_j-IfEAIQAg"; // <GPGSID>
        public const string event_esther_defeated = "CgkI5NK_j-IfEAIQDQ"; // <GPGSID>
        public const string achievement_wingman = "CgkI5NK_j-IfEAIQBQ"; // <GPGSID>
        public const string achievement_the_journey_begins = "CgkI5NK_j-IfEAIQAw"; // <GPGSID>
        public const string event_1p_match_started = "CgkI5NK_j-IfEAIQEQ"; // <GPGSID>
        public const string event_tok_senah_defeated = "CgkI5NK_j-IfEAIQDg"; // <GPGSID>
        public const string event_2p_match_started = "CgkI5NK_j-IfEAIQDw"; // <GPGSID>
        public const string event_safiya_defeated = "CgkI5NK_j-IfEAIQCA"; // <GPGSID>
        public const string event_1p_match_ended = "CgkI5NK_j-IfEAIQEg"; // <GPGSID>
        public const string event_eric_defeated = "CgkI5NK_j-IfEAIQDA"; // <GPGSID>

}

